"""
Example: Crossplane XRD for Harvester VM Provisioning

This shows how to define a Crossplane CompositeResourceDefinition (XRD)
that uses the xplane-harvester-vm KCL module.

The XRD defines the desired state, and the Composition uses the KCL module
to generate the actual Kubernetes resources.
"""

# Example XRD Definition (YAML format)
# This would be defined in your cluster:

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: harvestervms.example.com
spec:
  group: example.com
  names:
    kind: HarvesterVM
    plural: harvestervms
  claimNames:
    kind: HarvesterVMClaim
    plural: harvestervmclaims
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                # Basic configuration
                name:
                  type: string
                namespace:
                  type: string
                vmName:
                  type: string
                hostname:
                  type: string

                # PVC configuration
                pvcName:
                  type: string
                imageNamespace:
                  type: string
                imageId:
                  type: string
                storage:
                  type: string
                storageClass:
                  type: string
                volumeMode:
                  type: string
                  enum: [Filesystem, Block]
                accessModes:
                  type: array
                  items:
                    type: string

                # Secret configuration
                secretName:
                  type: string
                userdata:
                  type: string
                  description: Base64-encoded cloud-config
                networkdata:
                  type: string
                  description: Base64-encoded network-config

                # VM configuration
                osLabel:
                  type: string
                cpuCores:
                  type: integer
                  default: 4
                memory:
                  type: string
                networkName:
                  type: string

                # Control flags
                enablePvc:
                  type: boolean
                  default: true
                enableSecret:
                  type: boolean
                  default: true
                enableVm:
                  type: boolean
                  default: true
              required:
                - name

# Example Composition using xplane-harvester-vm KCL module
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: harvestervms.example.com
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: HarvesterVM
  mode: Pipeline
  pipeline:
    - step: harvester-resources
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: kcl.crossplane.io/v1alpha1
        kind: KCLInput
        spec:
          source: oci://ghcr.io/stuttgart-things/kcl-xplane-harvester-vm:latest
          # The KCL module receives the XR as option("params").oxr
          # Variables are extracted via: option("params")?.oxr?.spec.fieldName

# Example Resource Creation (User perspective)
---
apiVersion: example.com/v1alpha1
kind: HarvesterVM
metadata:
  name: dev2
spec:
  name: dev2
  namespace: production
  vmName: dev2-vm
  hostname: dev2.example.com
  description: Development environment VM

  # PVC configuration
  pvcName: dev2-disk-0
  imageNamespace: default
  imageId: image-ubuntu-22.04
  storage: 50Gi
  storageClass: longhorn
  volumeMode: Block

  # Secret (cloud-init)  # pragma: allowlist secret
  secretName: dev2-cloud-init  # pragma: allowlist secret
  userdata: |
    I2Nsb3VkLWNvbmZpZwpob3N0bmFtZTogZGV2Mg==

  # VM configuration
  osLabel: linux
  cpuCores: 8
  memory: 16Gi
  networkName: vms

  # Enabled all resources
  enablePvc: true
  enableSecret: true  # pragma: allowlist secret
  enableVm: true
