---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/platform-engineering-showcase/refs/heads/main/taskfiles/git.yaml

tasks:
  lint-repository:
    desc: Lint repository using Dagger blueprint function
    cmds:
      - |
        dagger call -m {{ .MODULE }}@{{ .VERSION }} {{ .FUNCTION }} \
        --src {{ .CODE_DIR }} \
        export --path {{ .EXPORT_PATH }}
    vars:
      MODULE: github.com/stuttgart-things/blueprints/repository-linting
      VERSION: v1.15.0
      FUNCTION: validate-multiple-technologies
      CODE_DIR: "./"
      EXPORT_PATH: /tmp/kcl-repo-findings.txt

  push-module:
    desc: Push KCL module using Dagger function
    cmds:
      - |
        MODULE_DIRS=$(find . -maxdepth 3 -type f -name 'kcl.mod' ! -path './tests/*' ! -path './.git/*' ! -path './.task/*' -exec dirname {} \; | sed 's|^\./||' | sort)

        if [ -z "$MODULE_DIRS" ]; then
          echo "No KCL modules found with kcl.mod files"
          exit 1
        fi

        MODULE_DIR=$(echo "$MODULE_DIRS" | gum choose --header "Select module directory:")

        if [ -z "$MODULE_DIR" ]; then
          echo "No module selected"
          exit 1
        fi

        MODULE_NAME=$(yq -p toml -r '.package.name' "${MODULE_DIR}/kcl.mod")

        dagger call -m {{ .MODULE }}@{{ .VERSION }} {{ .FUNCTION }} \
        --src "${MODULE_DIR}" \
        --module-name "${MODULE_NAME}" \
        --user env:GITHUB_USER \
        --password env:GITHUB_TOKEN \
        --address {{ .ADDRESS }}
    vars:
      MODULE: github.com/stuttgart-things/dagger/kcl
      VERSION: v0.42.0
      FUNCTION: push-module
      ADDRESS: oci://ghcr.io/stuttgart-things

  create:
    desc: Create new module
    cmds:
      - |
        MODULE_NAME=$(gum input --placeholder "Enter module name" --value "")
        mkdir -p "$MODULE_NAME" && cd "$MODULE_NAME"
        kcl mod init

        PROVIDER=$(gum choose "none" "crossplane-provider-kubernetes" "crossplane-provider-aws" "crossplane-provider-azure" --header "Select a provider to add:")
        if [ "$PROVIDER" != "none" ]; then
          kcl mod add "$PROVIDER"
        else
          echo "Skipping provider addition."
        fi
            yq -i '.modules += ["$MODULE_NAME"]' kcl.mod

  create-object-module-from-crd:
    desc: Convert CRDs to KCL
    vars:
      EXPORT_ROOT: ./models
    cmds:
      - |
        CRD_SOURCE=$(gum input --placeholder "Enter CRD source URL" \
        --prompt "CRD Source: ")
        MODULE_NAME=$(gum input --placeholder "Enter module name" \
        --prompt "Module Name: ")

        # Run dagger command with the provided CRD source

        dagger call -m github.com/stuttgart-things/dagger/kcl@v0.36.0 convert-crd \
          --crd-source "$CRD_SOURCE" \
          --progress plain \
          export --path={{ .EXPORT_ROOT }}/${MODULE_NAME}

        # Add module name to kcl.mod using yq
        yq -p toml -i '.package.name = "'"${MODULE_NAME}"'"' {{ .EXPORT_ROOT }}/${MODULE_NAME}/kcl.mod

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  tag:
    desc: Tag repo
    cmds:
      - task: commit
      - |
        echo "Enter to be created (remote) tag on the repository:"
        read TAG_NAME;
        git tag -a ${TAG_NAME} -m 'updated for ${TAG_NAME} on {{ .DATE }}'
        git push origin --tags
