---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml

tasks:
  lint-repository:
    desc: Lint repository using Dagger blueprint function
    cmds:
      - |
        dagger call -m {{ .MODULE }}@{{ .VERSION }} {{ .FUNCTION }} \
        --src {{ .CODE_DIR }} \
        export --path {{ .EXPORT_PATH }}
    vars:
      MODULE: github.com/stuttgart-things/blueprints/repository-linting
      VERSION: v1.15.0
      FUNCTION: validate-multiple-technologies
      CODE_DIR: "./"
      EXPORT_PATH: /tmp/kcl-repo-findings.txt

  push-module:
    desc: Push KCL module with version checking and kcl.mod update
    cmds:
      - |
        set -e

        # Find all KCL modules
        MODULE_DIRS=$(find . -maxdepth 3 -type f -name 'kcl.mod' \
          ! -path './tests/*' ! -path './.git/*' ! -path './.task/*' \
          -exec dirname {} \; | sed 's|^\./||' | sort)

        if [ -z "$MODULE_DIRS" ]; then
          echo "No KCL modules found with kcl.mod files"
          exit 1
        fi

        MODULE_DIR=$(echo "$MODULE_DIRS" | \
          gum choose --header "Select module directory:")

        if [ -z "$MODULE_DIR" ]; then
          echo "No module selected"
          exit 1
        fi

        # Get module name and current version
        MODULE_NAME=$(grep '^name' "${MODULE_DIR}/kcl.mod" | head -1 | cut -d'"' -f2)
        CURRENT_VERSION=$(grep '^version' "${MODULE_DIR}/kcl.mod" | head -1 | cut -d'"' -f2)

        echo "📦 Module: ${MODULE_NAME}"
        echo "   Current version in kcl.mod: ${CURRENT_VERSION}"
        echo

        # Check OCI registry for existing versions
        IMAGE="ghcr.io/stuttgart-things/${MODULE_NAME}"
        echo "🔍 Checking existing versions in ${IMAGE}..."

        TAGS=$(oras repo tags "${IMAGE}" 2>/dev/null || true)
        SEMVER_TAGS=$(echo "$TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || true)

        if [ -z "$SEMVER_TAGS" ]; then
          echo "⚠️  No released versions found in registry"

          # If no registry versions, use local version and increment minor
          if [ "${CURRENT_VERSION}" != "0.0.0" ]; then
            SUGGESTED_TAG=$(echo "v${CURRENT_VERSION}" | awk -F. '{
              sub(/^v/,"",$1);
              printf("v%d.%d.0\n",$1,$2+1)
            }')
            echo "   Using local version ${CURRENT_VERSION} → next minor: ${SUGGESTED_TAG}"
          else
            SUGGESTED_TAG="v0.1.0"
          fi
        else
          echo "📦 Released versions:"
          echo "$SEMVER_TAGS" | sort -V | sed 's/^/  - /'

          LATEST=$(echo "$SEMVER_TAGS" | sort -V | tail -n1)
          echo
          echo "✅ Latest released version: ${LATEST}"

          SUGGESTED_TAG=$(echo "$LATEST" | awk -F. '{
            sub(/^v/,"",$1);
            printf("v%d.%d.0\n",$1,$2+1)
          }')
        fi

        echo
        NEW_VERSION=$(gum input \
          --prompt "New version: " \
          --value "${SUGGESTED_TAG#v}")

        if [ -z "$NEW_VERSION" ]; then
          echo "❌ No version provided, exiting"
          exit 1
        fi

        NEW_TAG="v${NEW_VERSION}"
        echo
        echo "📝 Updating kcl.mod version from ${CURRENT_VERSION} to ${NEW_VERSION}..."
        sed -i "s/^version = .*/version = \"${NEW_VERSION}\"/" \
          "${MODULE_DIR}/kcl.mod"

        echo "✅ kcl.mod updated"
        echo

        # Push the module
        echo "🚀 Pushing KCL module:"
        echo "  Module : ${MODULE_DIR}"
        echo "  Name   : ${MODULE_NAME}"
        echo "  Tag    : ${NEW_TAG}"
        echo

        dagger call -m {{ .MODULE }}@{{ .VERSION }} {{ .FUNCTION }} \
        --src "${MODULE_DIR}" \
        --module-name "${MODULE_NAME}" \
        --user env:GITHUB_USER \
        --password env:GITHUB_TOKEN \
        --address "oci://${IMAGE%/*}" \
        --progress plain

        echo
        echo "✅ Push complete!"
    vars:
      MODULE: github.com/stuttgart-things/dagger/kcl
      VERSION: v0.42.0
      FUNCTION: push-module

  create:
    desc: Create new module
    cmds:
      - |
        MODULE_NAME=$(gum input --placeholder "Enter module name" --value "")
        mkdir -p "$MODULE_NAME" && cd "$MODULE_NAME"
        kcl mod init

        PROVIDER=$(gum choose "none" "crossplane-provider-kubernetes" \
          "crossplane-provider-aws" "crossplane-provider-azure" \
          --header "Select a provider to add:")
        if [ "$PROVIDER" != "none" ]; then
          kcl mod add "$PROVIDER"
        else
          echo "Skipping provider addition."
        fi
            yq -i '.modules += ["$MODULE_NAME"]' kcl.mod

  create-object-module-from-crd:
    desc: Convert CRDs to KCL
    vars:
      EXPORT_ROOT: ./models
    cmds:
      - |
        CRD_SOURCE=$(gum input --placeholder "Enter CRD source URL" \
        --prompt "CRD Source: ")
        MODULE_NAME=$(gum input --placeholder "Enter module name" \
        --prompt "Module Name: ")

        # Run dagger command with the provided CRD source

        dagger call -m github.com/stuttgart-things/dagger/kcl@v0.36.0 convert-crd \
          --crd-source "$CRD_SOURCE" \
          --progress plain \
          export --path={{ .EXPORT_ROOT }}/${MODULE_NAME}

        # Add module name to kcl.mod using yq
        yq -p toml -i '.package.name = "'"${MODULE_NAME}"'"' \
          {{ .EXPORT_ROOT }}/${MODULE_NAME}/kcl.mod

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | \
          sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  tag:
    desc: Tag repo
    cmds:
      - task: commit
      - |
        echo "Enter to be created (remote) tag on the repository:"
        read TAG_NAME;
        git tag -a ${TAG_NAME} -m 'updated for ${TAG_NAME} on {{ .DATE }}'
        git push origin --tags
