---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/platform-engineering-showcase/refs/heads/main/taskfiles/git.yaml

tasks:
  create:
    desc: Create new module
    cmds:
      - |
        MODULE_NAME=$(gum input --placeholder "Enter module name" --value "")
        mkdir -p "$MODULE_NAME" && cd "$MODULE_NAME"
        kcl mod init

        PROVIDER=$(gum choose "none" "crossplane-provider-kubernetes" "crossplane-provider-aws" "crossplane-provider-azure" --header "Select a provider to add:")
        if [ "$PROVIDER" != "none" ]; then
          kcl mod add "$PROVIDER"
        else
          echo "Skipping provider addition."
        fi
            yq -i '.modules += ["$MODULE_NAME"]' kcl.mod

  create-object-module-from-crd:
    desc: Convert CRDs to KCL
    vars:
      EXPORT_ROOT: ./models
    cmds:
      - |
        CRD_SOURCE=$(gum input --placeholder "Enter CRD source URL" \
        --prompt "CRD Source: ")
        MODULE_NAME=$(gum input --placeholder "Enter module name" \
        --prompt "Module Name: ")

        # Run dagger command with the provided CRD source

        dagger call -m github.com/stuttgart-things/dagger/kcl@v0.36.0 convert-crd \
          --crd-source "$CRD_SOURCE" \
          --progress plain \
          export --path={{ .EXPORT_ROOT }}/${MODULE_NAME}

        # Add module name to kcl.mod using yq
        yq -i '.name += ["'"${MODULE_NAME}"'"]' {{ .EXPORT_ROOT }}/${MODULE_NAME}/kcl.mod

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
