kcl_options:
  - key: params
    value:
      oxr:
        apiVersion: config.stuttgart-things.com/v1alpha1
        kind: Capability
        metadata:
          name: u26-rke2-1-capability
          namespace: default
        spec:
          clusterName: u26-rke2-1
          kubernetesProviderConfigRef: u26-rke2-1-kubernetes
          environment: labul
          vault:
            server: https://vault.infra.sthings-vsphere.labul.sva.de
          capabilities:
            ansible:
              enabled: true
              vault:
                mount: cicd-proxmox-labul
              placement:
                namespace: tekton-ci
                storageClass: openebs-hostpath
            proxmoxvm:
              enabled: true
              vault:
                mount: cicd-proxmox-labul
                secret: default
              placement:
                node: ul-pve01
                datastore: V5010-01-1
                bridge: vmbrvlan
                vlanTag: "102"
                pool: stuttgart-things
                templateVmId: "211"
      ocds: {}
      ctx: {}
