---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: ClaimTemplate
metadata:
  name: storageplatform-nfs
  title: Crossplane StoragePlatform NFS
  description: Deploys NFS CSI driver with StorageClass via Crossplane
  tags:
    - storage
    - crossplane
    - nfs
spec:
  type: storageplatform
  source: oci://ghcr.io/stuttgart-things/claim-xplane-storageplatform
  tag: 0.1.1
  parameters:
    - name: templateName
      title: Template
      type: string
      default: nfs

    - name: name
      title: Resource Name
      type: string
      default: nfs-storage
      pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

    - name: namespace
      title: Namespace
      type: string
      required: true
      default: default
      pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

    - name: targetClusterName
      title: Target Cluster
      type: string
      default: in-cluster

    - name: targetClusterScope
      title: Target Cluster Scope
      type: string
      default: Cluster
      enum:
        - Cluster
        - Namespaced

    - name: serverFQDN
      title: NFS Server
      type: string
      required: true

    - name: sharePath
      title: NFS Share Path
      type: string
      required: true

    - name: storageClass
      title: StorageClass Name
      type: string
      default: nfs-client

    - name: nfsVersion
      title: NFS CSI Driver Version
      type: string
      default: v4.11.0

    - name: nfsNamespace
      title: NFS CSI Namespace
      type: string
      default: kube-system

    - name: reclaimPolicy
      title: Reclaim Policy
      type: string
      default: Delete
      enum:
        - Delete
        - Retain

    - name: volumeBindingMode
      title: Volume Binding Mode
      type: string
      default: Immediate
      enum:
        - Immediate
        - WaitForFirstConsumer

    - name: mountOptions
      title: Mount Options
      type: string
      description: "Comma-separated list of mount options (e.g., vers=4.1,rsize=1048576)"
