---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: ClaimTemplate
metadata:
  name: storageplatform-openebs
  title: Crossplane StoragePlatform OpenEBS
  description: Deploys OpenEBS storage platform via Crossplane
  tags:
    - storage
    - crossplane
    - openebs
spec:
  type: storageplatform
  source: oci://ghcr.io/stuttgart-things/claim-xplane-storageplatform
  tag: 0.1.1
  parameters:
    - name: templateName
      title: Template
      type: string
      default: openebs
      hidden: true  # Won't be prompted, always uses default

    - name: name
      title: Resource Name
      type: string
      default: openebs-local
      pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

    - name: namespace
      title: Namespace
      type: string
      required: true
      default: default
      pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

    - name: targetClusterName
      title: Target Cluster
      type: string
      default: in-cluster

    - name: targetClusterScope
      title: Target Cluster Scope
      type: string
      default: Cluster
      enum:
        - Cluster
        - Namespaced

    - name: openebsVersion
      title: OpenEBS Version
      type: string
      default: "4.2.0"

    - name: openebsNamespace
      title: OpenEBS Namespace
      type: string
      default: openebs-system

    - name: enableLvm
      title: Enable LVM
      type: boolean
      default: false

    - name: enableZfs
      title: Enable ZFS
      type: boolean
      default: false

    - name: enableMayastor
      title: Enable Mayastor
      type: boolean
      default: false

    - name: enableVolumeSnapshots
      title: Enable Volume Snapshots
      type: boolean
      default: false

    - name: enableCsiNodeInitContainers
      title: Enable CSI Node Init Containers
      type: boolean
      default: false
      description: "Required for Mayastor"
